<div class="cart-total">
    <ul>
        <li>
            <a href="#">
                <span class="cart-icon">
                    <i class="fa fa-shopping-cart"></i>
                </span>
                <span class="cart-no">My cart: ({{count}})</span>
            </a>
            <div class="mini-cart-content">
                {{web_small_cart}}
            </div>
        </li>
    </ul>
</div>