<footer class="footer-area">
    <!-- footer-top-area start -->
    <div class="footer-top-area">
        <div class="container">
            <div class="row">
                <!-- footer-about start -->
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="footer-about">
                        <img src="{{assets_url}}img/logo/logo.jpg" style="width: 230px;" alt="" />
                        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamc</p>
                        <ul>
                            <li><i class="fa fa-map-marker"> </i> Addresss: 123 Pall Mall, London England</li>
                            <li><i class="fa fa-phone"> </i> Phone: <a href="tel:+1 901-218-8604"> +921321654 </a></li>
                            <li><i class="fa fa-envelope-o"> </i> Email: <a href="mailto:admin@invictagentalman.com">admin@invictagentalman.com</a></li>
                        </ul>
                    </div>
                </div>
                <!-- footer-about end -->
                <!-- footer-menu start -->
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="footer-menu">
                        <h3 class="widget-title">Customer Cate</h3>
                        <ul>
                            <li><a href="#">Contact US</a></li>
                            <li><a href="#">Sitemap</a></li>
                            <li><a href="#">Term & Conditions</a></li>
                            <li><a href="#">Gift & Vourchers</a></li>
                        </ul>
                    </div>
                </div>
                <!-- footer-menu end -->
                <!-- footer-menu start -->
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="footer-menu">
                        <h3 class="widget-title">Information</h3>
                        <ul>
                            <li><a href="#">Our Blog</a></li>
                            <li><a href="#">About Our Shop</a></li>
                            <li><a href="#">Secure Shopping</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>
                    </div>
                </div>
                <!-- footer-menu end -->
                <!-- newsletter start -->
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="newsletter footer-menu">
                        <h3 class="widget-title">Newsletter</h3>
                        <p>Subscribe to the Zonker mailing list to receive updates on new arrivals, special offers and other discount information</p>
                        <form action="#">
                            <div class="stay-us">
                                <input type="text" placeholder="Email" />
                                <button type="submit"><i class="fa fa-chevron-right"></i></button>
                            </div>
                        </form>
                        <div class="footer-icons">
                            <a href="#" data-toggle="tooltip" title="Facebook"><i class="fa fa-facebook"></i></a>
                            <a href="#" data-toggle="tooltip" title="Twitter"><i class="fa fa-twitter"></i></a>
                            <a href="#" data-toggle="tooltip" title="Tumblr"><i class="fa fa-tumblr"></i></a>
                            <a href="#" data-toggle="tooltip" title="Google-plus"><i class="fa fa-google-plus"></i></a>
                            <a href="#" data-toggle="tooltip" title="Dribbble"><i class="fa fa-dribbble"></i></a>
                        </div>
                    </div>
                </div>
                <!-- newsletter end -->
            </div>
        </div>
    </div>
    <!-- footer-top-area end -->
    <!-- footer-bottom-area start -->
    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="copyright">
                        <p>Copyright © 2018 <a href="#" target="_blank"> Invicta Gentleman</a>. All Rights Reserved</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- footer-bottom-area end -->
</footer>
