<nav id="dropdown">

    <ul>
        <li><a href="#">Suits</a>
            <ul class="sub-menu">
                <li><a href="{{base_url}}designSuit/1">DESIGN YOUR OWN</a></li>
                <li><a href="{{base_url}}outlet/1/1">SUIT COLLECTION</a></li>
                <li><a href="#">SUIT FABRICS</a></li>
            </ul>
        </li>

        <li><a href="{{base_url}}outlet/2/1">Shirts</a></li>
        <li><a href="{{base_url}}outlet/3/1">Blazers</a></li>
        <li><a href="{{base_url}}accessories/1/1">Accessories</a></li>
        <li><a href="{{base_url}}visitUs">Visit Us</a></li>
    </ul>

</nav>
