<footer class="footer-1" id="footer">
    <div class="vd_bottom ">
        <div class="container">
            <div class="row">
                <div class=" col-xs-12">
                    <div class="copyright">
                        Product Maker &copy; 2017
                    </div>
                </div>
            </div>
            <!-- row -->
        </div>
        <!-- container -->
    </div>
</footer>
