<header class="header-1" id="header">
    <div class="vd_top-menu-wrapper">
        <div class="container ">
            <div class="vd_top-nav vd_nav-width  ">
                <div class="vd_panel-header">
                    <div class="logo">
                        <a href="#"><img alt="logo" style="height:30px !important;" src="{{assets_url}}/img/logo.png"></a>
                    </div>
                    <!-- logo -->
                    <div class="vd_panel-menu  hidden-sm hidden-xs"
                         data-intro="<strong>Minimize Left Navigation</strong><br/>Toggle navigation size to medium or small size. You can set both button or one button only. See full option at documentation."
                         data-step=1>
            		                	<span class="nav-medium-button menu" data-toggle="tooltip"
                                              data-placement="bottom" data-original-title="Medium Nav Toggle"
                                              data-action="nav-left-medium">
	                    <i class="fa fa-bars"></i>
                    </span>

                	<span class="nav-small-button menu" data-toggle="tooltip" data-placement="bottom"
                          data-original-title="Small Nav Toggle" data-action="nav-left-small">
	                    <i class="fa fa-ellipsis-v"></i>
                    </span>

                    </div>
                    <div class="vd_panel-menu left-pos visible-sm visible-xs">

                        <span class="menu" data-action="toggle-navbar-left">
                            <i class="fa fa-ellipsis-v"></i>
                        </span>


                    </div>
                    <div class="vd_panel-menu visible-sm visible-xs">



                    </div>
                    <!-- vd_panel-menu -->
                </div>
                <!-- vd_panel-header -->

            </div>
            <div class="vd_container">
                <div class="row">
                    <div class="col-sm-5 col-xs-12">
                    </div>
                    <div class="col-sm-7 col-xs-12">
                        <div class="vd_mega-menu-wrapper">
                            <div class="vd_mega-menu pull-right">
                                <ul class="mega-ul">
                                   {{update_button}}
                                    <li id="top-menu-1" class="one-icon mega-li">
                                        <a href="{{base_url}}" class="mega-link" data-original-title="Logout" data-toggle="tooltip" data-placement="bottom">
                                            <span class="mega-icon">
                                                <i class="fa fa-sign-out"></i>
                                            </span>
                                        </a>
                                        <!-- vd_mega-menu-content -->
                                    </li>
                                </ul>
                                <!-- Head menu search form ends -->
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- container -->
    </div>
    <!-- vd_primary-menu-wrapper -->

</header>
