<div class="vd_navbar vd_nav-width vd_navbar-tabs-menu vd_navbar-left  ">
    <div class="navbar-menu clearfix">

        <h3 class="menu-title hide-nav-medium hide-nav-small">INVICTA GENTLEMAN</h3>

        <div class="vd_menu">
            <ul>

                <li>
                    <a href="{{base_url}}adminIndex">
                        <span class="menu-icon">
                            <i class="fa fa-dashboard"></i>
                        </span>
                        <span class="menu-text">Dashboard</span>
                    </a>
                </li>

                <li>
                    <a href="javascript:void(0);" data-action="click-trigger">
                        <span class="menu-icon">
                            <i class="fa fa-archive"></i>
                        </span>
                        <span class="menu-text">Products</span>
                            <span class="menu-badge">
                                <span class="badge vd_bg-black-30">
                                    <i class="fa fa-angle-down"></i>
                                </span>
                            </span>
                    </a>

                    <div class="child-menu" data-action="click-target">
                        <ul>
                            <li>
                                <a href="{{base_url}}adminAllProducts/1">
                                    <span class="menu-text">All Products</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{base_url}}addProduct">
                                    <span class="menu-text">Add New Product</span>
                                </a>
                            </li>
                        </ul>
                    </div>

                </li>

                <li>
                    <a href="javascript:void(0);" data-action="click-trigger">
                        <span class="menu-icon">
                            <i class="fa fa-archive"></i>
                        </span>
                        <span class="menu-text">Orders</span>
                            <span class="menu-badge">
                                <span class="badge vd_bg-black-30">
                                    <i class="fa fa-angle-down"></i>
                                </span>
                            </span>
                    </a>

                    <div class="child-menu" data-action="click-target">
                        <ul>
                            <li>
                                <a href="{{base_url}}adminAllOrders">
                                    <span class="menu-text">All Orders</span>
                                </a>
                            </li>
                        </ul>
                    </div>

                </li>

                <li>
                    <a href="javascript:void(0);" data-action="click-trigger">
                        <span class="menu-icon">
                            <i class="fa fa-archive"></i>
                        </span>
                        <span class="menu-text">Colors</span>
                            <span class="menu-badge">
                                <span class="badge vd_bg-black-30">
                                    <i class="fa fa-angle-down"></i>
                                </span>
                            </span>
                    </a>

                    <div class="child-menu" data-action="click-target">
                        <ul>
                            <li>
                                <a href="{{base_url}}colors">
                                    <span class="menu-text">Colors</span>
                                </a>
                            </li>
                        </ul>
                    </div>

                </li>


                <li>
                    <a href="javascript:void(0);" data-action="click-trigger">
                        <span class="menu-icon">
                            <i class="fa fa-archive"></i>
                        </span>
                        <span class="menu-text">Categories</span>
                            <span class="menu-badge">
                                <span class="badge vd_bg-black-30">
                                    <i class="fa fa-angle-down"></i>
                                </span>
                            </span>
                    </a>
                    <div class="child-menu" data-action="click-target">
                        <ul>
                            <li>
                                <a href="{{base_url}}adminAllCategories/1">
                                    <span class="menu-text">All Categories</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{base_url}}addCategory">
                                    <span class="menu-text">New Category</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>


                <li>
                    <a href="javascript:void(0);" data-action="click-trigger">
                        <span class="menu-icon">
                            <i class="fa fa-archive"></i>
                        </span>
                        <span class="menu-text">Accessories</span>
                        <span class="menu-badge">
                            <span class="badge vd_bg-black-30">
                                <i class="fa fa-angle-down"></i>
                            </span>
                        </span>
                    </a>
                    <div class="child-menu" data-action="click-target">
                        <ul>
                            <li>
                                <a href="{{base_url}}adminAllAccessories/1">
                                    <span class="menu-text">All Accessories</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{base_url}}addAccessory">
                                    <span class="menu-text">New Accessory</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>


                <li>
                    <a href="javascript:void(0);" data-action="click-trigger">
                        <span class="menu-icon">
                            <i class="fa fa-archive"></i>
                        </span>
                        <span class="menu-text">Collections</span>
                        <span class="menu-badge">
                            <span class="badge vd_bg-black-30">
                                <i class="fa fa-angle-down"></i>
                            </span>
                        </span>
                    </a>
                    <div class="child-menu" data-action="click-target">
                        <ul>
                            <li>
                                <a href="{{base_url}}allCollections">
                                    <span class="menu-text">All Collections</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{base_url}}addCollection">
                                    <span class="menu-text">Add Collection</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>


                <li>
                    <a href="javascript:void(0);" data-action="click-trigger">
                        <span class="menu-icon">
                            <i class="fa fa-archive"></i>
                        </span>
                        <span class="menu-text">Fabric</span>
                        <span class="menu-badge">
                            <span class="badge vd_bg-black-30">
                                <i class="fa fa-angle-down"></i>
                            </span>
                        </span>
                    </a>
                    <div class="child-menu" data-action="click-target">
                        <ul>
                            <li>
                                <a href="{{base_url}}adminAllFabrics">
                                    <span class="menu-text">All Fabrics</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{base_url}}addFabric">
                                    <span class="menu-text">Add Fabric</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>


                <li>
                    <a href="javascript:void(0);" data-action="click-trigger">
                        <span class="menu-icon">
                            <i class="fa fa-archive"></i>
                        </span>
                        <span class="menu-text">Lining</span>
                        <span class="menu-badge">
                            <span class="badge vd_bg-black-30">
                                <i class="fa fa-angle-down"></i>
                            </span>
                        </span>
                    </a>
                    <div class="child-menu" data-action="click-target">
                        <ul>
                            <li>
                                <a href="{{base_url}}adminAllLinings">
                                    <span class="menu-text">All Linings</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{base_url}}addLinings">
                                    <span class="menu-text">Add Lining</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

            </ul>
            <!-- Head menu search form ends -->
        </div>
    </div>
    <div class="navbar-spacing clearfix">
    </div>
    <div class="vd_menu vd_navbar-bottom-widget">
        <ul>
            <li>
                <a href="{{base_url}}adminLogout">
                    <span class="menu-icon">
                        <i class="fa fa-sign-out"></i>
                    </span>
                    <span class="menu-text">Logout</span>
                </a>

            </li>
        </ul>
    </div>
</div>